
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 6;
  public static final int PARD = 5;
  public static final int MULT = 3;
  public static final int error = 1;
  public static final int SUMA = 2;
  public static final int IDENT = 7;
  public static final int PARI = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "MULT",
  "PARI",
  "PARD",
  "NUM",
  "IDENT"
  };
}

